"""email verification

Revision ID: 032f9e0828cc
Revises: 22c7dcfb5d91
Create Date: 2026-09-08 18:30:50.995439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032f9e0828cc'
down_revision: Union[str, None] = '22c7dcfb5d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(),
                                     nullable=False, server_default='false'))
    op.alter_column('users', 'email_verified', server_default=None)
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # accounts that predate verification were created deliberately
    op.execute("UPDATE users SET email_verified = true, verified_at = now()")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
