"""stored sla deadline with pause tracking

Revision ID: 22c7dcfb5d91
Revises: 566f0ccf3679
Create Date: 2026-09-07 19:29:40.978294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c7dcfb5d91'
down_revision: Union[str, None] = '566f0ccf3679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('paused_seconds', sa.Integer(),
                                       nullable=False, server_default='0'))
    op.alter_column('tickets', 'paused_seconds', server_default=None)
    op.create_index(op.f('ix_tickets_due_at'), 'tickets', ['due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_due_at'), table_name='tickets')
    op.drop_column('tickets', 'paused_seconds')
    op.drop_column('tickets', 'paused_at')
    op.drop_column('tickets', 'due_at')
    # ### end Alembic commands ###
