"""oidc auth source

Revision ID: 3483acafc1fb
Revises: 9680020dd9b3
Create Date: 2026-09-16 03:43:45.199522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3483acafc1fb'
down_revision: Union[str, None] = '9680020dd9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oidc_subject', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_oidc_subject'), 'users', ['oidc_subject'], unique=False)
    # autogenerate does not detect CHECK constraint changes
    op.drop_constraint("ck_user_auth_source", "users", type_="check")
    op.create_check_constraint(
        "ck_user_auth_source", "users", "auth_source IN ('local', 'ldap', 'oidc')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oidc_subject'), table_name='users')
    op.drop_column('users', 'oidc_subject')
    op.execute("UPDATE users SET auth_source = 'local' WHERE auth_source = 'oidc'")
    op.drop_constraint("ck_user_auth_source", "users", type_="check")
    op.create_check_constraint(
        "ck_user_auth_source", "users", "auth_source IN ('local', 'ldap')"
    )
    # ### end Alembic commands ###
