"""store oidc id token for logout

Revision ID: 4cfc4101b5e3
Revises: 3483acafc1fb
Create Date: 2026-09-16 03:54:11.614232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfc4101b5e3'
down_revision: Union[str, None] = '3483acafc1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oidc_id_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oidc_id_token')
    # ### end Alembic commands ###
