"""settings table and admin role

Revision ID: 566f0ccf3679
Revises: 84f22c5e13a3
Create Date: 2026-09-07 19:18:14.945911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566f0ccf3679'
down_revision: Union[str, None] = '84f22c5e13a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###
    op.drop_constraint("ck_user_role", "users", type_="check")
    op.create_check_constraint(
        "ck_user_role", "users", "role IN ('admin', 'agent', 'customer')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
    op.execute("UPDATE users SET role = 'agent' WHERE role = 'admin'")
    op.execute("UPDATE users SET role_override = NULL WHERE role_override = 'admin'")
    op.drop_constraint("ck_user_role", "users", type_="check")
    op.create_check_constraint(
        "ck_user_role", "users", "role IN ('agent', 'customer')"
    )
