"""baseline schema

Revision ID: 5d84f258c30e
Revises: 
Create Date: 2026-09-07 12:44:06.085778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d84f258c30e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS ticket_ref_seq START WITH 1047")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requester', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('org', sa.String(length=120), nullable=False),
    sa.Column('assignee', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('P1', 'P2', 'P3', 'P4')", name='ck_ticket_priority'),
    sa.CheckConstraint("status IN ('New', 'Open', 'Waiting on customer', 'Resolved', 'Closed')", name='ck_ticket_status'),
    sa.CheckConstraint("track IN ('saas', 'it')", name='ck_ticket_track'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tickets_email', 'tickets', ['email'], unique=False)
    op.create_index(op.f('ix_tickets_ref'), 'tickets', ['ref'], unique=True)
    op.create_index('ix_tickets_status_priority', 'tickets', ['status', 'priority'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('comment', 'note', 'system')", name='ck_event_kind'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_ticket_id'), 'events', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS ticket_ref_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_ticket_id'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_tickets_status_priority', table_name='tickets')
    op.drop_index(op.f('ix_tickets_ref'), table_name='tickets')
    op.drop_index('ix_tickets_email', table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
