"""soft delete on events

Revision ID: 7eacddfca4c7
Revises: 5d84f258c30e
Create Date: 2026-09-07 12:45:38.657309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eacddfca4c7'
down_revision: Union[str, None] = '5d84f258c30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('deleted_by', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'deleted_by')
    op.drop_column('events', 'deleted_at')
    # ### end Alembic commands ###
