"""outbox queue

Revision ID: 84f22c5e13a3
Revises: 13d633a5cedd
Create Date: 2026-09-07 18:46:29.183407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f22c5e13a3'
down_revision: Union[str, None] = '13d633a5cedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=200), nullable=False),
    sa.Column('to_name', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ticket_ref', sa.String(length=16), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'sending', 'sent', 'failed', 'suppressed')", name='ck_outbox_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_status_next', 'outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_ticket_ref'), 'outbox', ['ticket_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_ticket_ref'), table_name='outbox')
    op.drop_index('ix_outbox_status_next', table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
