"""scheduled tickets

Revision ID: 9680020dd9b3
Revises: e79450ed7f1b
Create Date: 2026-09-14 13:21:20.473042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9680020dd9b3'
down_revision: Union[str, None] = 'e79450ed7f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recur_every', sa.Integer(), nullable=True),
    sa.Column('recur_unit', sa.String(length=16), nullable=True),
    sa.Column('recur_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('track', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=2), nullable=False),
    sa.Column('requester_email', sa.String(length=200), nullable=False),
    sa.Column('assignee', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('once', 'recurring')", name='ck_schedule_kind'),
    sa.CheckConstraint("priority IN ('P1', 'P2', 'P3', 'P4')", name='ck_schedule_priority'),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'failed')", name='ck_schedule_status'),
    sa.CheckConstraint("track IN ('saas', 'it')", name='ck_schedule_track'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedules_due', 'schedules', ['status', 'next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedules_due', table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
