"""original description as an event

Revision ID: e79450ed7f1b
Revises: 689f50d92bc8
Create Date: 2026-09-14 12:51:38.226040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79450ed7f1b'
down_revision: Union[str, None] = '689f50d92bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_original', sa.Boolean(),
                                     nullable=False, server_default='false'))
    op.alter_column('events', 'is_original', server_default=None)
    # every existing ticket's description becomes its first event, so
    # attachments can hang off it like any other message
    op.execute("""
        INSERT INTO events (ticket_id, at, actor, kind, body, is_original)
        SELECT id, created_at, requester, 'comment', body, true
        FROM tickets
        WHERE NOT EXISTS (
            SELECT 1 FROM events e WHERE e.ticket_id = tickets.id AND e.is_original
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_original')
    # ### end Alembic commands ###
